myproject/myapp/urls.py
from django.urls import path,include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('',views.Index.as_view(), name='index'),
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    path('post_detail/<int:pk>',views.PostDetail.as_view(), name = 'post_detail'),
    path('post_update/<int:pk>',views.PostUpdate.as_view(), name = 'post_update'),
    path('post_delete/<int:pk>',views.PostDelete.as_view(), name = 'post_delete'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

myproject/myapp/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField('タイトル',max_length=50)
    content = models.TextField('内容',max_length=1000)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


# Create your models here.

myproject/myapp/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

myproject/myapp/views.py
from django.shortcuts import render, resolve_url
from django.http import HttpResponse
from django.views.generic import TemplateView, CreateView, DetailView,UpdateView,DeleteView
from .models import Post
from django.urls import reverse_lazy
from .forms import PostForm



class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self,*args,**kwargs):
        content = super().get_context_data
        post_list = Post.objects.all().order_by('-created_at')
        context={
            'post_list':post_list,
        }
        return context


class PostCreate(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')

class PostDetail(DetailView):
    model = Post

class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm
    def get_success_url(self):
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])

class PostDelete(DeleteView):
    model = Post
    def get_success_url(self):
        return resolve_url('myapp:index')


# Create your views here.

myproject/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css" rel="stylesheet" />
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"></script>
</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#navbarExample01" aria-controls="navbarExample01" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarExample01">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">mogura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin" target="_blank">管理画面</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'myapp:post_create' %}">新規投稿</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navbar -->






    </header>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

myproject/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block content %}


<!-- Jumbotron -->
<div class="p-5 text-center bg-light">
    <h1 class="mb-3">Heading</h1>
    <h4 class="mb-3">Subheading</h4>
    <a class="btn btn-primary" href="" role="button">Call to action</a>
</div>
<!-- Jumbotron -->
</header>


<div class="row row-cols-1 row-cols-md-2 g-4">
    {% for item in post_list %}
    <div class="col">
        <div class="card">
            <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top"
                alt="Hollywood Sign on The Hill" />
            <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card-text">
                    This is a longer card with supporting text below as a natural lead-in to
                    additional content. This content is a little bit longer.
                </p>
                <a href="{% url 'myapp:post_detail' item.id %}" type="button" class="btn btn-success">アクセス</a>
            </div>
        </div> 
    </div>
    {% endfor %}

</div>

{% endblock %}

myproject/myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2>Post削除</h2>
        <br>
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p>以下の内容を本当に削除しますか</p>
                <input type="submit" class="btn btn-outline-danger" value="削除する">
            </form>
        </div>

        <br>
        <p>タイトル</p>
        {{ object.title }}
        <hr>
        <p>内容</p>
        {{ object.content }}

    </div>
</div>

{% endblock %}

myproject/myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="row">
    <div class="cols-md-9">
        <br>
        <div class="card">
            <img src="https://mdbcdn.b-cdn.net/img/new/standard/nature/184.webp" class="card-img-top"
                alt="Fissure in Sandstone" />
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">{{object.content}}</p>
                <a href="{% url 'myapp:post_update' object.id %}" class="btn btn-primary">更新</a>
                <a href="{% url 'myapp:post_delete' object.id %}" class="btn btn-danger">削除</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}image.png

myproject/myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2>登録ページ</h2>
        <br>

        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>タイトル</label>
                {{ form.title }}
            </div>
            <br>
            <div class="form-group">
                <label>内容</label>
                {{ form.content }}
            </div>
            <br>
            <button type="submit" class="btn btn-success">保存</button>
            <br>
        </form>

    </div>
</div>

{% endblock %}